-- MySQL Script generated by MySQL Workbench
-- Wed Apr  9 15:21:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id` INT NOT NULL,
  `idPessoas` INT NOT NULL,
  `Telefone 1` VARCHAR(45) NOT NULL,
  `Telefone 2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idPessoas_idx` (`idPessoas` ASC) VISIBLE,
  CONSTRAINT `idPessoas`
    FOREIGN KEY (`idPessoas`)
    REFERENCES `mydb`.`Pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoas` (
  `id` INT NOT NULL,
  `id_hospedes` INT NOT NULL,
  `id_telefone` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idHospedes_idx` (`id_hospedes` ASC) VISIBLE,
  CONSTRAINT `idHospedes`
    FOREIGN KEY (`id_hospedes`)
    REFERENCES `mydb`.`Hospedes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTelefone`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Telefone` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospedes` (
  `id` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idPessoa_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `idPessoas`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `mydb`.`Pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservas` (
  `id` INT NOT NULL,
  `idHospedes` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idHospedes_idx` (`idHospedes` ASC) VISIBLE,
  CONSTRAINT `idHospedes`
    FOREIGN KEY (`idHospedes`)
    REFERENCES `mydb`.`Hospedes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamentos` (
  `id` INT NOT NULL,
  `id_Reservas` INT NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idReservas_idx` (`id_Reservas` ASC) VISIBLE,
  CONSTRAINT `idReservas`
    FOREIGN KEY (`id_Reservas`)
    REFERENCES `mydb`.`Reservas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quartos` (
  `idQuartos` INT NOT NULL,
  `Numero` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Preço_Diaria` INT NOT NULL,
  PRIMARY KEY (`idQuartos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quartos_reservados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quartos_reservados` (
  `id` INT NOT NULL,
  `id_hospede` INT NOT NULL,
  `data_checkin` DATETIME NOT NULL,
  `data_checkout` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `idReservas`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Reservas` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idQuartos`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Quartos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
